DROP TABLE IF EXISTS `mech` CASCADE;

CREATE TABLE `mech` (
	`id` BIGINT PRIMARY KEY AUTO_INCREMENT, 
	`year` INTEGER CHECK (year<=3000 AND year>=2000),
	`name` VARCHAR(255) NOT NULL UNIQUE,
	`model` VARCHAR(255), 
	`weight` INTEGER
);